markdownExploder: true
qa:
  qaLocation: .agents/qa
prd:
  prdFile: .agents/prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: .agents/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: .agents/architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: .agents/architecture
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - .agents/architecture/coding-standards.md
  - .agents/architecture/tech-stack.md
  - .agents/architecture/source-tree.md
devDebugLog: .ai/debug-log.md
devStoryLocation: .agents/stories
slashPrefix: BMad
